# Generated by Django 5.2.8 on 2025-11-30 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('certifications', models.TextField()),
                ('video_resume_url', models.URLField(blank=True, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('badges', models.JSONField(default=list)),
                ('care_score', models.FloatField(default=5.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
